spring:
  data:
    mongodb:
      username: aligorithm
      password: aligorithm
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090